# Generated by Django 4.1.5 on 2023-02-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_payment_orderproduct_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addres_line_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
